services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - ENVIRONMENT=dockerized
  postgres:
     image: postgres
     restart: always
     user: postgres
#     volumes:
#       - db-data:/var/lib/postgresql/data
     env_file:
       - .env
     expose:
       - 5432
     healthcheck:
       test: [ "CMD", "pg_isready" ]
       interval: 10s
       timeout: 5s
       retries: 5

#volumes:
# db-data:
